source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'pg'
gem 'decent_exposure'
gem 'haml'
gem 'haml-rails'
gem 'sunspot_rails'

group :development, :test, :console do
  gem 'rails3-generators'
  gem 'ruby-debug19'
  gem 'mongrel', '>=1.2.0.pre2'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'pickle'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'spork'
  gem 'launchy'
  gem 'factory_girl_rails', '1.1.beta1'
  gem 'factory_girl', '2.0.0.beta2'
  gem 'wirble'
  gem 'prawn'
  gem 'delorean'
  gem 'awesome_print', :require => 'ap'
  gem 'delorean'
  gem 'ffaker'
end

