source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'pg'
gem 'decent_exposure'
gem 'haml'
gem 'haml-rails'
gem 'meta_search'
gem 'foreigner'
gem 'sunspot_rails', '>=1.2.1'

group :development, :test, :console do
  gem 'rails3-generators'
  gem 'ruby-debug19'
  gem 'mongrel', '>=1.2.0.pre2'
  gem 'capybara'
  gem 'database_cleaner', '>=0.6.0'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'pickle'
  gem 'rspec', '>=2.4.0'
  gem 'rspec-rails', '>=2.4.0'
  gem 'spork'
  gem 'launchy'
  #gem 'capybara-envjs'
  gem 'factory_girl', '2.0.0.beta1'
  gem 'wirble'
  gem 'prawn'
  gem 'delorean'
  gem 'awesome_print', :require => 'ap'
  gem 'delorean'
  gem 'ffaker'
end

